# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zanerhon/capigrad

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zanerhon/capigrad

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zanerhon/capigrad/CMakeFiles /home/zanerhon/capigrad//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zanerhon/capigrad/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mie

# Build rule for target.
mie: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mie
.PHONY : mie

# fast build rule for target.
mie/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/build
.PHONY : mie/fast

src/data.o: src/data.cpp.o
.PHONY : src/data.o

# target to build an object file
src/data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/data.cpp.o
.PHONY : src/data.cpp.o

src/data.i: src/data.cpp.i
.PHONY : src/data.i

# target to preprocess a source file
src/data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/data.cpp.i
.PHONY : src/data.cpp.i

src/data.s: src/data.cpp.s
.PHONY : src/data.s

# target to generate assembly for a file
src/data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/data.cpp.s
.PHONY : src/data.cpp.s

src/features.o: src/features.cpp.o
.PHONY : src/features.o

# target to build an object file
src/features.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/features.cpp.o
.PHONY : src/features.cpp.o

src/features.i: src/features.cpp.i
.PHONY : src/features.i

# target to preprocess a source file
src/features.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/features.cpp.i
.PHONY : src/features.cpp.i

src/features.s: src/features.cpp.s
.PHONY : src/features.s

# target to generate assembly for a file
src/features.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/features.cpp.s
.PHONY : src/features.cpp.s

src/live.o: src/live.cpp.o
.PHONY : src/live.o

# target to build an object file
src/live.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/live.cpp.o
.PHONY : src/live.cpp.o

src/live.i: src/live.cpp.i
.PHONY : src/live.i

# target to preprocess a source file
src/live.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/live.cpp.i
.PHONY : src/live.cpp.i

src/live.s: src/live.cpp.s
.PHONY : src/live.s

# target to generate assembly for a file
src/live.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/live.cpp.s
.PHONY : src/live.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model.o: src/model.cpp.o
.PHONY : src/model.o

# target to build an object file
src/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/model.cpp.o
.PHONY : src/model.cpp.o

src/model.i: src/model.cpp.i
.PHONY : src/model.i

# target to preprocess a source file
src/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/model.cpp.i
.PHONY : src/model.cpp.i

src/model.s: src/model.cpp.s
.PHONY : src/model.s

# target to generate assembly for a file
src/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/model.cpp.s
.PHONY : src/model.cpp.s

src/nn.o: src/nn.cpp.o
.PHONY : src/nn.o

# target to build an object file
src/nn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/nn.cpp.o
.PHONY : src/nn.cpp.o

src/nn.i: src/nn.cpp.i
.PHONY : src/nn.i

# target to preprocess a source file
src/nn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/nn.cpp.i
.PHONY : src/nn.cpp.i

src/nn.s: src/nn.cpp.s
.PHONY : src/nn.s

# target to generate assembly for a file
src/nn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/nn.cpp.s
.PHONY : src/nn.cpp.s

src/trainer.o: src/trainer.cpp.o
.PHONY : src/trainer.o

# target to build an object file
src/trainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/trainer.cpp.o
.PHONY : src/trainer.cpp.o

src/trainer.i: src/trainer.cpp.i
.PHONY : src/trainer.i

# target to preprocess a source file
src/trainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/trainer.cpp.i
.PHONY : src/trainer.cpp.i

src/trainer.s: src/trainer.cpp.s
.PHONY : src/trainer.s

# target to generate assembly for a file
src/trainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mie.dir/build.make CMakeFiles/mie.dir/src/trainer.cpp.s
.PHONY : src/trainer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mie"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/features.o"
	@echo "... src/features.i"
	@echo "... src/features.s"
	@echo "... src/live.o"
	@echo "... src/live.i"
	@echo "... src/live.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/nn.o"
	@echo "... src/nn.i"
	@echo "... src/nn.s"
	@echo "... src/trainer.o"
	@echo "... src/trainer.i"
	@echo "... src/trainer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

